spring :

  application:
    name: todoApp

  datasource:
    url: jdbc:mysql://localhost:3306/todo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: oblivion0610
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.type: trace
